# Generated by Django 5.2.5 on 2026-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_vehicle_cost_per_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="qr_image",
        ),
    ]
