# Generated by Django 5.2.5 on 2026-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_remove_vehicle_qr_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
