# Generated by Django 5.2.5 on 2026-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_remove_reservation_payment_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="dropoff_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
