# Generated by Django 5.2.5 on 2026-03-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_reservation_dropoff_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
