# Generated by Django 5.2.5 on 2026-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_reservation_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "available"),
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("completed", "completed"),
                    ("finished", "finished"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
