# Generated by Django 5.2.5 on 2026-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_acc", "0004_alter_otp_otp_alter_otp_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
